/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-26 03:03:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/./components/sidebar.jsp", Long.valueOf(1545183882000L));
    _jspx_dependants.put("jar:file:/E:/ymt/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HelloWorld/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425949870000L));
    _jspx_dependants.put("/./components/menu.jsp", Long.valueOf(1545183882000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1545183882000L));
    _jspx_dependants.put("/./components/banner.jsp", Long.valueOf(1545183882000L));
    _jspx_dependants.put("/./components/header.jsp", Long.valueOf(1545183882000L));
    _jspx_dependants.put("/./components/footer.jsp", Long.valueOf(1545183882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <link rel=\"icon\" href=\"./img/favicon.ico\">\n");
      out.write("\n");
      out.write("    <title>Blog Template for Bootstrap</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap core CSS -->\n");
      out.write("    <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom styles for this template -->\n");
      out.write("<!--     <link href=\"https://fonts.googleapis.com/css?family=Playfair+Display:700,900\" rel=\"stylesheet\"> -->\n");
      out.write("    <link href=\"./css/blog.css\" rel=\"stylesheet\">\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("      <header class=\"blog-header py-3\">\n");
      out.write("        <div class=\"row flex-nowrap justify-content-between align-items-center\">\n");
      out.write("          <div class=\"col-4 pt-1\">\n");
      out.write("            <a class=\"btn btn-sm btn-outline-primary\" href=\"newpost.jsp\">New post</a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-4 text-center\">\n");
      out.write("            <a class=\"blog-header-logo text-dark\" href=\"index.jsp\">我的博客</a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-4 d-flex justify-content-end align-items-center\">\n");
      out.write("            <a class=\"text-muted\" href=\"#\">\n");
      out.write("              <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"mx-3\"><circle cx=\"10.5\" cy=\"10.5\" r=\"7.5\"></circle><line x1=\"21\" y1=\"21\" x2=\"15.8\" y2=\"15.8\"></line></svg>\n");
      out.write("            </a>\n");
      out.write("            \n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </header>");
      out.write("\n");
      out.write("\n");
      out.write("\t\t");
      out.write("\n");
      out.write("      <div class=\"nav-scroller py-1 mb-2\">\n");
      out.write("        <nav class=\"nav d-flex justify-content-between\">\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">World</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">U.S.</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">Technology</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">Design</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">Culture</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">Business</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">Politics</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">Opinion</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">Science</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">Health</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">Style</a>\n");
      out.write("          <a class=\"p-2 text-muted\" href=\"#\">Travel</a>\n");
      out.write("        </nav>\n");
      out.write("      </div>");
      out.write("\n");
      out.write("\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("<!--       <div class=\"jumbotron p-3 p-md-5 text-white rounded bg-dark\"> -->\n");
      out.write("<!--         <div class=\"col-md-6 px-0\"> -->\n");
      out.write("<!--           <h1 class=\"display-4 font-italic\">Title of a longer featured blog post</h1> -->\n");
      out.write("<!--           <p class=\"lead my-3\">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p> -->\n");
      out.write("<!--           <p class=\"lead mb-0\"><a href=\"#\" class=\"text-white font-weight-bold\">Continue reading...</a></p> -->\n");
      out.write("<!--         </div> -->\n");
      out.write("<!--       </div> -->\n");
      out.write("\n");
      out.write("      <div class=\"row mb-2\">\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <div class=\"card flex-md-row mb-4 shadow-sm h-md-250\">\n");
      out.write("            <div class=\"card-body d-flex flex-column align-items-start\">\n");
      out.write("              <strong class=\"d-inline-block mb-2 text-primary\">World</strong>\n");
      out.write("              <h3 class=\"mb-0\">\n");
      out.write("                <a class=\"text-dark\" href=\"#\">Featured post</a>\n");
      out.write("              </h3>\n");
      out.write("              <div class=\"mb-1 text-muted\">Nov 12</div>\n");
      out.write("              <p class=\"card-text mb-auto\">This is a wider card with supporting text below as a natural lead-in to additional content.</p>\n");
      out.write("              <a href=\"#\">Continue reading</a>\n");
      out.write("            </div>\n");
      out.write("            <img class=\"card-img-right flex-auto d-none d-lg-block\" data-src=\"holder.js/200x250?theme=thumb\" alt=\"Card image cap\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <div class=\"card flex-md-row mb-4 shadow-sm h-md-250\">\n");
      out.write("            <div class=\"card-body d-flex flex-column align-items-start\">\n");
      out.write("              <strong class=\"d-inline-block mb-2 text-success\">Design</strong>\n");
      out.write("              <h3 class=\"mb-0\">\n");
      out.write("                <a class=\"text-dark\" href=\"#\">Post title</a>\n");
      out.write("              </h3>\n");
      out.write("              <div class=\"mb-1 text-muted\">Nov 11</div>\n");
      out.write("              <p class=\"card-text mb-auto\">This is a wider card with supporting text below as a natural lead-in to additional content.</p>\n");
      out.write("              <a href=\"#\">Continue reading</a>\n");
      out.write("            </div>\n");
      out.write("            <img class=\"card-img-right flex-auto d-none d-lg-block\" data-src=\"holder.js/200x250?theme=thumb\" alt=\"Card image cap\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <main role=\"main\" class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-8 blog-main\">\n");
      out.write("          <h3 class=\"pb-3 mb-4 font-italic border-bottom\">\n");
      out.write("            From the Firehose \t\t\t          \n");
      out.write("          </h3>\n");
      out.write("\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${\"PostServlet\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null) + (((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${\"PostServlet\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("listposts", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("author", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.author }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("pageNo", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pageNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()), out, false);
      out.write("\t\n");
      out.write("\t\t\t\n");
      out.write("          <nav class=\"blog-pagination\">\n");
      out.write("            <a class='btn btn-outline-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pageNo+1<pageCount ? \"primary \" : \"secondary disabled\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' href=\"index.jsp?pageNo=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pageNo+1<pageCount ? param.pageNo+1 : param.pageNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Older</a>\n");
      out.write("            <a class='btn btn-outline-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pageNo-1 >= 0 ? \"primary \" : \"secondary disabled\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' href=\"index.jsp?pageNo=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pageNo-1 >= 0 ? param.pageNo-1 : 0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Newer</a>\n");
      out.write("          </nav>\n");
      out.write("\n");
      out.write("        </div><!-- /.blog-main -->\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("<aside class=\"col-md-4 blog-sidebar\">\n");
      out.write("  <div class=\"p-3 mb-3 bg-light rounded\">\n");
      out.write("    <h4 class=\"font-italic\">About</h4>\n");
      out.write("    <p class=\"mb-0\">This is a blog system <em>DEMO</em> for JavaWeb Course.</p>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"p-3\">\n");
      out.write("    <h4 class=\"font-italic\">Archives</h4>\n");
      out.write("    <ol class=\"list-unstyled mb-0\">\n");
      out.write("      <li><a href=\"#\">March 2014</a></li>\n");
      out.write("      <li><a href=\"#\">February 2014</a></li>\n");
      out.write("      <li><a href=\"#\">January 2014</a></li>\n");
      out.write("      <li><a href=\"#\">December 2013</a></li>\n");
      out.write("      <li><a href=\"#\">November 2013</a></li>\n");
      out.write("      <li><a href=\"#\">October 2013</a></li>\n");
      out.write("      <li><a href=\"#\">September 2013</a></li>\n");
      out.write("      <li><a href=\"#\">August 2013</a></li>\n");
      out.write("      <li><a href=\"#\">July 2013</a></li>\n");
      out.write("      <li><a href=\"#\">June 2013</a></li>\n");
      out.write("      <li><a href=\"#\">May 2013</a></li>\n");
      out.write("      <li><a href=\"#\">April 2013</a></li>\n");
      out.write("    </ol>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"p-3\">\n");
      out.write("    <h4 class=\"font-italic\">Elsewhere</h4>\n");
      out.write("    <ol class=\"list-unstyled\">\n");
      out.write("      <li><a href=\"#\">GitHub</a></li>\n");
      out.write("      <li><a href=\"#\">Twitter</a></li>\n");
      out.write("      <li><a href=\"#\">Facebook</a></li>\n");
      out.write("    </ol>\n");
      out.write("  </div>\n");
      out.write("</aside><!-- /.blog-sidebar -->");
      out.write("\n");
      out.write("\n");
      out.write("      </div><!-- /.row -->\n");
      out.write("\n");
      out.write("    </main><!-- /.container -->\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("    <footer class=\"blog-footer\">\n");
      out.write("      <p>Online: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${onlineCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" / Total: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("      <p>Blog template built for <a href=\"https://getbootstrap.com/\">Bootstrap</a> by <a href=\"https://twitter.com/mdo\">@mdo</a>.</p>\n");
      out.write("      <p>\n");
      out.write("        <a href=\"#\">Back to top</a>\n");
      out.write("      </p>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap core JavaScript\n");
      out.write("    ================================================== -->\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script>window.jQuery || document.write('<script src=\"./js/jquery-slim.min.js\"><\\/script>')</script>\n");
      out.write("    <script src=\"./js/popper.min.js\"></script>\n");
      out.write("    <script src=\"./js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"./js/holder.min.js\"></script>\n");
      out.write("    <script>\n");
      out.write("      Holder.addTheme('thumb', {\n");
      out.write("        bg: '#55595c',\n");
      out.write("        fg: '#eceeef',\n");
      out.write("        text: 'Thumbnail'\n");
      out.write("      });\n");
      out.write("    </script>");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /./components/header.jsp(17,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty User}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t            Welcome, <a href=\"userprofile.jsp\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${User.stuName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>&nbsp;            \n");
          out.write("\t            <a class=\"btn btn-sm btn-outline-secondary\" href=\"LogoutServlet\">Logout</a>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /./components/header.jsp(21,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty User }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t            <a class=\"btn btn-sm btn-outline-secondary\" href=\"login.jsp\">Login</a>&nbsp;\n");
          out.write("\t            <a class=\"btn btn-sm btn-outline-secondary\" href=\"register.jsp\">Register</a>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
